-- CONSULTAS PARA A CRIAÇÃO DOS GRÁFICOS

-- QUANTIDADE DE AUTORES DO GÊNERO MASCULINO, FEMININO E DESCONHECIDO
SELECT COUNT(*) FROM autor WHERE  genero = 1;
SELECT COUNT(*) FROM autor WHERE genero = 2;
SELECT COUNT(*) FROM autor WHERE genero = 3;
